language: node_js
node_js:
- lts/erbium
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
before_script:
- yarn global add @vue/cli @vue/cli-service push-dir
- yarn install
script:
- yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  target-branch: gh-pages
  github_token: $GITHUB_TOKEN
  keep_history: true
  edge: true
  verbose: true
  on:
    branch: master
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=ff87f64ef8a735978a2a180e7809c70b055d71a01cefe3b2b1d82b51444ad5cf
