language: node_js
node_js:
- lts/erbium
env:
  GITHUB_TOKEN:
    secure: q8gHYyL921VBY/tgcmDAnnotzyfTHY/iHl7EIiv0DFjO/aTyN1WfkRbaME/Ux33hNdlOBhVhU43DBaYXeL7ykQ43+sbX+CjroWrq0e6bKURruqJM8AzgMhE6dnXo+OWIq4KMHBihh/vCid1rjWpTlMU4e/6KMY5I3GFTAQpTjagCbVgs7y+zNLXgFW3mOo6rFaID0zqw837M5Yre7y0SlGRAgDgzGLwzmsreGrDcXx7owPiCSrnAj2yVWUkz7Fkzh85tsS19u2xZ+htbN4w25YgpNmkXjs+2y/cv3E3tQyTQ4vlT19oo5WvI01cmDMshydN3ktJ9xQzUpNMn7a7ELm6lgDuC84oS1ILFGrjl2LjAV8mF6sW1Gl5hIOV0HJbse8Vknf6+xmpukYWOA6pYlUCW8ySdM1rbK9HBoxOdSCUQrc3FGBsnULIlgO8slPtjIP1XrB9XJHhf3i9glnpvTOi6ZNBIClfJZnoKl5249VLiya4mN7KUzPIWOnlVKGyWFpdWvmrUsg6aA86FpkXZ3R1w/hXiMM7sO6MUyvBy1T0a6/xzE2lTt8qYSvN8QyEzCoCUM0bebNKkxKc5fVMe7u5eu5O2WcZlMTP/AfCtnm2o1FWM4FYsUx64jV2Ml5tEdFxZlW84nQSTNhmu0VaWp10jefjLKFRRgLFtKKRrLfw=
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- ".ci/check_travis_deploy_vars.sh"
cache:
  yarn: true
before_script:
- yarn global add @vue/cli @vue/cli-service push-dir
- yarn install
- ls node_modules
script:
- yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  edge: true
  verbose: true
  on:
    branch: master
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=ff87f64ef8a735978a2a180e7809c70b055d71a01cefe3b2b1d82b51444ad5cf
